### ISSUE TITLE
Alterative route declaration

### ISSUE THREAD

**Issue by DaleJefferson** [kogosoftwarellc/express-openapi#12]
The only thing I don't like about express-openapi is the "convention based programming", I found very confusing and limiting.

I would prefer a simple javascript api doc with embedded handlers.

```
openapi.initialize({
    app: app,
    swagger: '2.0',
    basePath: '/v1',
    info: {
        title: 'App',
        version: '1.0.0',
    },
    paths: {
        '/users': {
            get: {
                parameters: [],
                responses: {
                    200: {
                        description: 'Get all users',
                        schema: {
                            type: 'array',
                            items: {
                                title: 'User',
                                type: 'object',
                                properties: {
                                    name: {
                                        type: 'string'
                                    }
                                }
                            },
                        }
                    }
                },
                handler(req, res) {
                    res.json([{name: 'Dale'}]);
                }
            },
            post: {
                handler(req, res) {
                    res.status(201);
                }
            }
        },
        '/users/{userId}': {
            get: {
                handler(req, res) {
                    res.json({name: 'Dale'});
                }
            }
        }
    }
});
```

You can use modules to split up the code, you have the full javascript language to generate routes or do whatever you like.

```
openapi.initialize({
    app: app,
    swagger: '2.0',
    basePath: '/v1',
    info: {
        title: 'App',
        version: '1.0.0',
    },
    paths: {
        '/users': require('./routes/users'),
        '/messages': {
            'get': require('./routes/messages').get
        },
        '/books': createCrudEndpoints("Books"),
        ...require('./lotsOfEndpointsUsingSpread')
    }
});
```

The existing convention based system could be used to build this structure internally.

**Comment by jsdevel** [comment]
So you can define paths in `apiDoc.paths`, and `express-openapi` will inherit from it, except for handlers.

What you would consider limiting, I would consider freeing.

Consider that you never have to duplicate a path, as it's entirely inferred from fs.

**Comment by jsdevel** [comment]
Also, you're documentation is kept up to date for users.  So if you delete a handler, you don't have to worry about your docs getting out of sync.  This is what bothers me about other frameworks that expect a monolithic json document or yaml doc to descript their apis.

**Comment by jsdevel** [comment]
Re-opening as express-openapi should aim to be as un-opinionated as possible to follow express's purpose `Fast, unopinionated, minimalist web framework for Node.js`.

**Comment by MugeSo** [comment]
OpenAPI spec has [`$ref` for `Path Object`](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#fixed-fields-4)

**Comment by DaleJefferson** [comment]
Thanks for re-opening this, it sounds like we could pull out the current convention over configuration router part of express-openapi into a separate middleware. 

BTW I've successfully used a few of the express-openapi middleware with Koa, the middleware strategy you have chosen works really nicely.

**Comment by jsdevel** [comment]
@DaleJefferson glad to hear the middleware strategy is working out for you!

I've had a few thoughts related to closing out this ticket:

* Add a new argument to the initialization args that specifies either a module or a directory (haven't decided which would be more friendly).
* This argument will define the operation handlers for the provided `apiDoc`.
* Operation handlers are referenced via `operationId` in the `apiDoc`.

**Comment by mika-fischer** [comment]
A related issue is that the reliance on fs-routes makes it totally impossible to package an app using express-openapi using webpack or similar tools. I'd like to be able to provide express-openapi with a list mapping urls to module paths or already loaded modules.

**Comment by jsdevel** [comment]
@mika-fischer PRs are always welcome!

**Comment by mika-fischer** [comment]
@jsdevel I might give it a go. But what would your preferred API look like?

My idea would be to make the `paths` option optional, and add a new option (maybe `routes` or `urls`(?)) and allow to pass an array of objects: `[ { route: 'foo', module: require('foo') }, ... ]` or `[ { route: 'foo', path: 'foo' }, ... ]`, similar to what fs-routes generates.

That way most of the code could be reused...

**Comment by jsdevel** [comment]
@mika-fischer I think the `paths` option array could also contain objects, and if no strings are in the array then we can skip the fs-routes call.  Thoughts?

**Comment by mika-fischer** [comment]
Yes, that also sounds fine, I'll see if I can implement this this week.

**Comment by jsdevel** [comment]
@DaleJefferson see the great work @mika-fischer did in #60.  I feel it closes this issue.  Thoughts?

**Comment by DaleJefferson** [comment]
Thanks @mika-fischer this looks great, I will happily close this issue
