### ISSUE TITLE
Looking for feedback

### ISSUE THREAD

**Issue by jsdevel** [kogosoftwarellc/express-openapi#3]
This issue is to request feedback from the community so `express-openapi` may be improved.  For any who wish not to be apart of this, please comment herein with `please remove me` and I'll delete any comment herein containing your @ mention.

**Comment by jsdevel** [comment]
@hilkeheremans  would you be willing to try `express-openapi` out and give me some feedback?  Thank you!

**Comment by hilkeheremans** [comment]
@jsdevel Too bad I didn't see this earlier; I had just forked swaggerize-express and stripped off the validation to circumvent the issue. Still, express-openapi looks interesting as well so I'll give it a go.

Just as an FYI, I will be combining this with swagger-express-middleware.

**Comment by jsdevel** [comment]
Sounds good!  `express-openapi` leverages `jsonschema` to the max, so you should find it to be pretty stable.  Looking forward to your feedback!

**Comment by hilkeheremans** [comment]
Seems to work perfectly for a very simple use case. FYI, we are using this in what most devs would probably call an enterprise-grade application, with a public API described by OpenAPI. We're still working on the plumbing and robustness. Over the next few weeks we'll be hooking up all our business logic etc, so feedback will get more interesting at that point.

Some quick observations. I'm putting them here as they are not feature requests/bug reports, just discussion points and a FYI for users who might want to move from swaggerize to express-openapi.
- Path resolution for the handlers seems to be relative to the working directory (standard behavior for '.'). This is fine for me but a minor caveat.
- The example in README.md uses a require to a .js file, which depends on a module.exports. At that point you can't directly use output from any swagger editor - you need to convert the .json to .js. Fortunately, you can just ```  apiDoc: require('./api-doc.json')```which works just as well. Might want to make this clear in the docs?
- If you insist on using .js just for the ability to comment, perhaps ```json5 ``` (https://github.com/aseemk/json5) is an option instead? This is backwards compatible with json without need for any conversion. It's not a full community standard yet but is quite popular and even supported in ```node-config```

**Comment by jsdevel** [comment]
> Over the next few weeks we'll be hooking up all our business logic etc, so feedback will get more interesting at that point.

Looking forward to it!

> Path resolution for the handlers seems to be relative to the working directory (standard behavior for '.'). This is fine for me but a minor caveat.

It can either be relative _or_ absolute.  Relative is based on the working directory of the running process.  Should this be called out in the docs somehow?

> The example in README.md uses a require to a .js file, which depends on a module.exports. At that point you can't directly use output from any swagger editor - you need to convert the .json to .js. Fortunately, you can just apiDoc: require('./api-doc.json')which works just as well. Might want to make this clear in the docs?

You can actually use json or js.  `.initialize()` just needs a parsed javascript object that is your api definition.  But yea, calling this out in the docs would be better.

> If you insist on using .js just for the ability to comment, perhaps json5...

Haven't heard of json5!  Looks pretty cool.  Again, updating the docs here would likely be good.

Thanks for the feedback!  I'll spend this week adding more clarification to the docs around these points.

**Comment by jsdevel** [comment]
@skindc should you have any issues with `swaggerize-express`, I'd be really interested to get your feedback on `express-openapi`.  The benefits of this framework are that it is entirely built on top of jsonschema which is more standard in a swagger (openapi) sense.

**Comment by hilkeheremans** [comment]
@jsdevel It seems I was a little too enthusiastic; express-openapi currently also does NOT handle recursive definitions. See kogosoftwarellc/express-openapi-validation#1 for more details.

**Comment by jsdevel** [comment]
@hilkeheremans see my response https://github.com/kogosoftwarellc/express-openapi-validation/issues/1#issuecomment-173632203.

I also updated the tests in this project to use recursion and it works.  See `test/sample-projects/basic-usage/api-doc.js`.

**Comment by jsdevel** [comment]
@rcherny, @rochal Just an FYI, `express-openapi` returns batched validation errors.  I'd love to see you try it and leave any feedback you may have.

**Comment by rcherny** [comment]
Hey @jsdevel I've tried it but had some issues with what I was precisely looking to do. Overall it looked like a nice set up. I'm trying to basically mock a swagger-based API with node.js and have validation that resembles what a .NET WebAPI back-end would be returning. I've got endpoints and all set up with Swaggerize-Express but the validation bypasses the handlers and I'm a relative ExpressJS noob so I'm trying to tweak the final output back to the client. We expect a `200` and a collection of validation errors on the front-end.

I'm certain there's a way to do this, but I'm just getting started... but when I tried express-openapi I got odd behavior since my swagger spec is already defined, paths and all — I wasn't looking to define the paths in code, just augment them. The moment I put a code-level API handler in the endpoint disappeared from the Swagger UI for some reason.

**Comment by rcherny** [comment]
@jsdevel sorry I should also have said, I'd be totally game for dropping `express-openapi-validation` into an existing ExpressJS set up but I'd need to:

1. drop it in as middleware
1. have it augment pre-existing paths
1. have it do it's "magic validation" and then augment it with `express-openapi-response-validation`

But I haven't had enough time to get that working so I had to move on for the moment.

Are there any examples in the [Tests](https://github.com/kogosoftwarellc/express-openapi-validation/tree/master/test/data-driven) that would show effectively what I need?

I'm 100% certain there's a way to do this, but I just haven't had time to figure it out.

**Comment by jsdevel** [comment]
@rcherny I think what you may be looking to do is intercept the validation errors, and change the status code.  If so, put some error catching middleware (defined with 4 parameters) as the last middleware in your chain like so:

```
app.use(function(err, req, res, next) {
  console.log(err);
  err.status = 200;
  res.status(200).json(err);
});
```

**Comment by rcherny** [comment]
Hey @jsdevel that's exactly what I ended up doing, more or less. The issue though is really that the `err` that comes back should have multiple errors listed, and other frameworks thus far are only giving me one. That said, I haven't tried the `express-openapi` modules listed above yet.

**Comment by jsdevel** [comment]
I think you'll be pleasantly surprised :smile:

**Comment by jsdevel** [comment]
@rcherny checkout the multiple errors returned in this data driven test: https://github.com/kogosoftwarellc/express-openapi-validation/blob/master/test/data-driven/fail-multiple-invalid-path-params.js

**Comment by jsdevel** [comment]
@asaf not sure if you're using `swaggerize-express`, but `express-openapi` should handle empty strings just fine.

**Comment by rcherny** [comment]
Hey @jsdevel I am using `swaggerize-express` — main thing is I'm unsure where to tap into it to use `express-openapi-validation` instead — as I have an api.json file with the rules in it, and the examples for openapi seem to include validation inside the code. Given more time I might just move the whole thing over, but for this current sprint I'm on, this may have to suffice. Otherwise, this does sound superior :)

**Comment by jsdevel** [comment]
> main thing is I'm unsure where to tap into it to use express-openapi-validation instead

You'll find with `swaggerize-express` that it isn't possible currently to disable input validation.  If you add `express-openapi-validation` to your project as is, you'll incur the cost of double validation which isn't good.

> Given more time I might just move the whole thing over, but for this current sprint I'm on, this may have to suffice. Otherwise, this does sound superior :)

I understand deadlines completely.  `express-openapi` was borne because the maintainers of `swaggerize` just weren't very responsive to issues.  You'll find the migration path to be very painless.  Let me know if I can help.

**Comment by rcherny** [comment]
@jsdevel re: the validation issue with Swaggerize ... yeah it's buried pretty deep in the code, I was afraid of that. No I certainly don't want double validation. 

If you could describe / document how to use `ecpress-openapi` with the definitions, paths, and rules in an external file, I'd be grateful. What I recall is the paths that I had file handlers for defined in the file system vanished from Swagger-UI.

But I could be mistaken. I may have time later this week to revisit.

**Comment by rcherny** [comment]
Sigh. Fat thumbed that on my phone. Sorry. `express` **

**Comment by jsdevel** [comment]
@rcherny I have a sample project that's really straight forward.  Check it out https://github.com/kogosoftwarellc/express-openapi/tree/master/test/sample-projects/basic-usage.

**Comment by MugeSo** [comment]
Hi @jsdevel!
This project has more simple, readable, beautiful code than `swaggerize-` :smile:
I have a high expectation for this :laughing: 

BTW, it seems `parameters` property of [path item object ](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#path-item-object)is not supported.
It makes api definition simpler! Especially, defining parameter in path.

**Comment by jsdevel** [comment]
@MugeSo parameters should be supported, unless I'm not understanding what you mean.

**Comment by MugeSo** [comment]
@jsdevel 
> unless I'm not understanding what you mean.

sorry, I'm not so good at English :pensive:
I just intended to say how important `parameters` property is.

**Comment by jsdevel** [comment]
@MugeSo no worries.  So `parameters` is supported.  See this example: https://github.com/kogosoftwarellc/express-openapi/blob/master/test/sample-projects/basic-usage/api-routes/users/%7Bid%7D.js#L45

What's probably throwing you off is that you define it in your handler files.

> This project has more simple, readable, beautiful code than swaggerize- :smile:

I'm glad you think so!

**Comment by MugeSo** [comment]
@jsdevel It's `parameter` of [operation object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operationObject), I said `parameter` of [path item object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathItemObject).

**Comment by jsdevel** [comment]
Ah ha!  I understand now!  Cool!  I didn't know swagger supported that.  I should be able to add that support easily.  Basically just concat the 2 arrays (path parameters and operation parameters).  I'll add this support tonight most likely.

**Comment by MugeSo** [comment]
great!

**Comment by jsdevel** [comment]
@MugeSo added path parameters with https://github.com/kogosoftwarellc/express-openapi/commit/e6e1835addfbb3476df64da7969b088be049bab3.  Thanks again for the feedback!

**Comment by MugeSo** [comment]
@jsdevel thanks for quick action!
However, it seems not satisfy the specification.

the [specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathItemObject) says:
> These parameters can be overridden at the operation level, but cannot be removed there. The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location.

On the other hand, e6e1835 just concat `parameters` and then duplicated validation  will be built for a key(a combination of a name and location).
 So, it should be overridden by a key.

**Comment by jsdevel** [comment]
Hey, thanks for the reference!  Let me fix that real quick.

**Comment by jsdevel** [comment]
@MugeSo fixed it with https://github.com/kogosoftwarellc/express-openapi/commit/a4bb78376added0301ea1a1486c183c6634636ca.  Also beefed up the tests.  Thanks again!

**Comment by MugeSo** [comment]
@jsdevel cool! you are great quick at work!

**Comment by jsdevel** [comment]
Just added the ability to completely configure middleware.  See https://github.com/kogosoftwarellc/express-openapi#configuring-middleware.

**Comment by MugeSo** [comment]
@jsdevel Will security feature be implement until 1.x?
Security feature mean handling of `security` property([security requirement object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#securityRequirementObject)) [of [swagger object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#swagger-object) and [operation object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#operation-object) and `securityDefinition`([security definition object](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-definitions-object)) property of swagger object.

If not, i need one of flowing feature to handle those properties :

- custom middleware builder handling.
- accessibility to built api doc from out of `openapi.initilize` function.

**Comment by jsdevel** [comment]
@MugeSo 

> Will security feature be implement until 1.x?

I haven't had plans to implement security, but I'm open to suggestions.  My thought process thus far is that you could just handle it with middleware.

### At the global level

```
app.use(mySecurityMiddleware);
openapi.initialize({
   ...
});
```

### At the operation level

```
module.exports = {
  get: [securityMiddleware, function(req, res){res.status(200).json(/*something*/);}]
};
```

As I'm typing this though, I realize that these approaches don't really scope well.  Like, you can't just add middleware at the apiDoc/path level alone.

## Full circle

What about a vendor extension?  I realize we're talking about security middleware, but I can see other middleware being needed when building an api.  Maybe something like `'x-express-openapi-additional-middleware': [securityMiddleware]`.  I see it being scoped, similar to the other vendor extensions implemented thus far.

**Comment by MugeSo** [comment]
@jsdevel thanks for response.
IMHO, this library should not handle securities because it is too complex.
And there is many good authorization/authentication libraries.
So, what I need is just ability to bridge built api doc (including operation doc) and such libraries.

OTTOMH:
```js
app.use(mySecurityMiddleware);
var apiDoc = openapi.initialize({ ... });
mySecurityMiddleware.attachApiDoc(apiDoc);
```

**Comment by jsdevel** [comment]
> IMHO, this library should not handle securities because it is too complex.  And there is many good authorization/authentication libraries.

I couldn't agree more.  This approach also conforms to the [single responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle).

> So, what I need is just ability to bridge built api doc (including operation doc) and such libraries.

I think returning the built apiDoc from `.initialize()` would be a good approach.  I wonder though if we should return an object instead?

```
var initializedApi = openapi.initialize({ ... });
mySecurityMiddleware.attachApiDoc(initializedApi.apiDoc);
```

I can see additional properties being useful in the future.  Thoughts?

**Comment by MugeSo** [comment]
>  I wonder though if we should return an object instead?
> I can see additional properties being useful in the future. Thoughts?

It look nice!

**Comment by jsdevel** [comment]
@MugeSo try `0.8.0`.

**Comment by jsdevel** [comment]
Added scoped middleware with `v0.9.0`.

**Comment by jsdevel** [comment]
@talvor @Lucg I'd be curious to know what your thoughts are on the way `express-openapi` handles middleware.  You should be able to handle security in a super flexible manner.  See [Configuring Middleware](https://github.com/kogosoftwarellc/express-openapi#configuring-middleware).

**Comment by jsdevel** [comment]
@phillip-hall saw that you had an open PR against `express-swaggerize` to move route middleware before route validation.  I feel this is an important feature that would be good to incorporate into `express-openapi` somehow.

I'd be curious to know if you would take a look at the way `express-openapi` currently handles middleware, and what a clean addition to the api would look like?

I'm kind of thinking there are 3 possible scenarios:

1. You want middleware to be _prepended_ to route middleware.
2. You want middleware to be _appended_ to route middleware.
3. You want the ability to insert coercion, defaults, and validation middleware somewhere in the middleware pipeline.

Based on that, I'd think a couple of vendor extensions would do the trick.  Perhaps something like:

* `'x-express-openapi-prepends-middleware': true`
* `'x-express-openapi-appends-middleware': true`
* `'x-express-openapi-inserts-middleware': true`

If the last option is given, then I feel the middleware handler for the operation could use strings, something like this:

```javascript
[myMiddleware1, 'defaults', 'coercion', myMiddleware2, 'validation', function(req, res) {
  // my response handler
}];
```

Curious to know what your thoughts are on that.

**Comment by talvor** [comment]
@jsdevel I have not seen this module and I like the direct it is going.  

I think a better approach would be to replace/extend `x-express-openapi-additional-middleware` with `x-express-openapi-middleware-before-validation` and `x-express-openapi-middleware-after-validation`.

These would allow for a route definition to define middleware that executes before and after any validation/security middleware.

What do you think?

**Comment by jsdevel** [comment]
I think that would be good.  My thoughts about your proposal mainly have to do with defaults and coercion, and the potential complexity of 6 options for all 3.  I.E.

* `x-express-openapi-middleware-before-defaults`
* `x-express-openapi-middleware-after-defaults`
* `x-express-openapi-middleware-before-coercion`
* `x-express-openapi-middleware-after-coercion`
* `x-express-openapi-middleware-before-validation`
* `x-express-openapi-middleware-after-validation`

Even though this would add more vendor extensions, I do feel it is less complex than my first thoughts so I'm now more inclined to go in this direction.

**Comment by talvor** [comment]
@jsdevel Yes, this sounds very flexible.  

Another option would be to just export the `defaults`, `coercion` and `validation` middleware functions and let the developer setup the middleware order they require for each api route definition. Similar to your previous idea.

**Comment by hsablonniere** [comment]
Hey @jsdevel.

Your projet and especially the different middlewares it contains look very interesting. I've also looked around and found other projects that do similar stuffs (in different ways).

I wanted to know how you compare your project to **swagger-tools**? It's 2 years old and they've started a big split/refactor in different modules. I asked them [how they compare to your project](https://github.com/apigee-127/swagger-tools/issues/335#issuecomment-184309399) but I was also curious to know more from you.

Thanks.

**Comment by jsdevel** [comment]
@talvor 
> Another option would be to just export the defaults, coercion and validation middleware functions and let the developer setup the middleware order they require for each api route definition. Similar to your previous idea.

The only way I know to do that is with strings in the array, but that would break the concept of scoped middleware pretty quickly.  I think I'm leaning more towards your suggestion as defined [here](https://github.com/kogosoftwarellc/express-openapi/issues/3#issuecomment-184139310).

@hsablonniere  I've only looked at `swagger-tools` briefly, but here's my take on it having looked at it's source code only briefly (I hope I am corrected if I am wrong):

* `swagger-tools` revolves around a single JSON file to describe your API.  This is similar to a lot of options out there.  Where `express-openapi` differs, is that it relies on conventions to spread your API document throughout your path controllers.  The benefits of this approach are:
  * you avoid one giant monolithic API document
  * you are able to use `scoped` middleware.  By scoped I mean you can define middleware at the API level, the path level, or directly for an operation.
* your application is easier to understand as documentation for operations is directly in the file where they are defined.
* `express-openapi` is developed against the  [single responsibility principle](https://en.wikipedia.org/wiki/Single_responsibility_principle).  This means that the source code is incredibly easy to understand and maintain.  In fact, all middleware (defaults, coercion, input validation, and response validation), is handled by middleware in separate repositories.  `express-openapi` itself is a single `index.js` file.
* `express-openapi` maintains 100% coverage and utilizes data driven testing to the max.
* `express-openapi` does not concern itself with the browser.  It is expected that you will host Swagger UI elsewhere or use petstore.swagger.io to view your API.

**Comment by hsablonniere** [comment]
Thanks @jsdevel. This is crystal clear.

For our product, we're considering your project because we **really** want to avoid the monolithic API document. We want the path definitions to be in the same file as the handler code (and their middlewares).

To be honest, I'm not a huge fan of the API you proposed in this very project but it's really a matter of taste :wink:

* Because of the nature of our API, we don't organize our routers the way you do.
* We really want an API that's on top of separate modules exposing routers.

I think, we're going to use all the different middlewares you've created. They really fit our needs. We just have to build a new way to define the routers and do a similar code as your to merge all the path definitions into the main API document.

I'll keep you updated on our progress this could interest others...

Thx.

**Comment by jsdevel** [comment]
No problem and good luck!

**Comment by whitlockjc** [comment]
swagger-tools works with JSON, YAML and can even work with computed JavaScript objects to describe your API so it's not limited to just a single, monolithic JSON file.  Yes, there is [currently a bug](https://github.com/apigee-127/swagger-tools/issues/227) *(with workaround)* with relative references that makes it a little more difficult to break things up but there is a very simple workaround and the swagger-tools replacement won't have this issue of course.  *(If you want more information about this issue, it's heavily documented in the link complete with a simple workaround.)*

The original purpose of swagger-tools' middleware was to make _"Swagger Driven APIs"_ a reality because no middlewares at that time enabled that.  A _"Swagger Driven API"_ is an API that uses the information described in your Swagger document to handle the minutiae of API development.  *(Request/response validation, parameter coercion/processing, security, ...)*  Since your Swagger document already describes your request/response contract, swagger-tools uses this information to basically enforce your request/response contract for you without you having to do any of it.

At the time swagger-tools was created, no middlewares enabled this type of API.  Most middlewares at that time required you to mix API description and code, and generated your Swagger document as a build/runtime artifact.  So instead of your controller's route handler being `module.export.handleRoute = function (req, res, next) {`, with middlewares like the ones I describe your route handlers looked more like `module.exports.handleRoute = {spec: {...}, handler: function (req, res, next) {`, or something like it.  To many, this is mixing concerns but I can understand as a developer how this approach might be useful because I write code of course.  That being said, there is no right or wrong answer when it comes to mixing or separating your API design and implementation.  But it does have an impact on the tooling you choose.

One more thing, I do think some of the concerns/comparisions that @jsdevel brought up are valid, like swagger-tools the npm module violating the _"single responsibility principle"_.  The good news is we've been aware of this for some time and that's the reason behind us [deprecating/replacing swagger-tools](https://github.com/apigee-127/swagger-tools/issues/335).  Some of his opinions are somewhat subjective:

* _"your application is easier to understand as documentation for operations is directly in the file where they are defined"_
* _"the source code is incredibly easy to understand and maintain"_

I find these subjective because they are based solely upon opinion and your opinion could differ based on your answer to this question: Do I want to separate API description/design from API implementation?  *(Heck, your opinion on these things could differ based on whether your a developer or not, whether you work on this API or not, ...  Forcing someone to view your code to understand your API might not fly well with everyone.)*  Your answer will dictate your decision as to what style of tools make the most sense.

Choose wisely and may the odds be ever in your favor.

**Comment by jsdevel** [comment]
@hsablonniere 

On this note

> Because of the nature of our API, we don't organize our routers the way you do.

How would you prefer to organize your route files?

**Comment by hsablonniere** [comment]
Thanks @whitlockjc for your message. Yes, it's a matter of opinion. In my team, we all share the *"put the doc next to the code"* mantra. It's the only way (for us) to enforce the fact that doc is always up to date. We'll definitely monitor the evolution on the sway projects.

**Comment by hsablonniere** [comment]
@jsdevel We're still experimenting. More info soon... :smile:

**Comment by jsdevel** [comment]
Added support for custom json schema formats with https://github.com/kogosoftwarellc/express-openapi/commit/b01fc0ea6da2440c3292c29c42fc5806b0c1932b.

Here's an example:

```
{
  "type": "string",
  "format": "myCustomFormat"
}
```

```
openapi.initialize({
  apiDoc: require('./api-doc'),
  app: app,
  customFormats: {
    myCustomFormat: function(input) {
      return input === 'my special format';// return a boolean for valid
    }
  }
});
```

**Comment by MugeSo** [comment]
@jsdevel I wrote type definition of this package for typescript.
https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/express-openapi

If you want, you can port it ;)
And add `typings` into package.json.
https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages

P.S.
... I know my type definition does not support `customFormats` yet.

**Comment by jsdevel** [comment]
Super awesome @MugeSo!  I'd love to include it.  Can you submit a PR?

**Comment by MugeSo** [comment]
@jsdevel OK, I'll do it.

**Comment by jsdevel** [comment]
@dcolens I'd love to get your feedback on `express-openapi`.  It was inspired by `swaggerize-express`, but has fewer pain points.  Your migration path should be trivial.

**Comment by jsdevel** [comment]
`express-openapi` now adds tags found in operation docs that are missing in your apiDoc tags array.  See https://github.com/kogosoftwarellc/express-openapi/commit/b94068ff9c873c560971af9cde9a9bb83a8e8a22

**Comment by jsdevel** [comment]
Added support for error middleware that is scoped to the API's basePath property with 9f4b733340cd3aefe699e5231e9a62ce60d1b5c4.

**Comment by jsdevel** [comment]
@johnleetechnology I noticed that you were having issues using $ref in swaggerize-routes.  I'd be interested in having you try express-openapi to see if it handles your use case.

**Comment by jsdevel** [comment]
Added `del` alias for `delete` and recognizing api docs on method handlers in array middleware with `v0.14.0`.

**Comment by jsdevel** [comment]
@rkarodia if you're looking for a swagger module that allows you to transform validation errors, checkout `express-openapi`.  See [args.errorTransformer](https://github.com/kogosoftwarellc/express-openapi#argserrortransformer) for more details.

**Comment by MugeSo** [comment]
I wish something like:
```js
// in "routes/my/handler.js"
var openapi = require('express-openapi');
module.exports.post = function(req, res, next) {
   req.status(204)
       .header('Content-Location',
           openapi.resolveRoute('someOperationId', {paramName: 'foo'})
       .json({progress: 0});
}
```

**Comment by MugeSo** [comment]
How about to add [app.mountpath](http://expressjs.com/en/4x/api.html#app.mountpath) to `apiDoc.baseUrl`.

**Comment by jsdevel** [comment]
@MugeSo adding app.mountpath would be good.  Can you submit a PR for that?

**Comment by jsdevel** [comment]
@MugeSo what would the use case of `openapi.resolveRoute` be?

**Comment by MugeSo** [comment]
@jsdevel OK, I'll send PR for app.mountpath

`resolveRoute` is to generate URL by `operationId` for  `Location` and `Content-Location` header or other links.
It keeps programmer away from path except when touch directory or file name.

Now I think `res.resolveRoute` would be bettter.

**Comment by jsdevel** [comment]
Oh I see what you mean.  Cool!

Can you submit a PR for that as well?

**Comment by MugeSo** [comment]
@jsdevel No, I can't because `resolveRoute` is just idea yet.
We need more considering and discussion.

**Comment by jsdevel** [comment]
@MugeSo makes sense.  I feel `getOperationURL` makes more sense then as your intent is to get a URL by an operation name.

**Comment by jsdevel** [comment]
Thanks to @MugeSo, `args.externalSchemas` is now supported in `v0.19.0`.

**Comment by jsdevel** [comment]
@jacob-zneider just saw the issue you submitted on swaggerize-express.  The main issue with that library is that it doesn't rely on jsonschema.  Swagger/openapi are built on jsonschema, so any library not build on top of that is almost doomed to fail.  I'd love to know what you think about `express-openapi` after giving it a shot.

**Comment by jsdevel** [comment]
@marcofranssen `express-openapi` used `express-openapi-response-validation` middleware.  I'd love to see what you think of it. (saw that you posted a related issue in `swaggerize-express`.
