### ISSUE TITLE
Dynamic routes are being loaded before static routes

### ISSUE THREAD

**Issue by phillip-hall** [kogosoftwarellc/express-openapi#37]
The following file structure results in the routes being loaded in the wrong order. Note the use of the {id} pattern as windows does not support ":" in file names.

```
routes/
      `home.js
      |
      `users/
            `{id}.js
            `query.js
```
This results in route /users/{id} being defined before /users/query which is not the desired outcome.

I have submitted a PR to the node-fs-routes repo that fixes this.  [https://github.com/jsdevel/node-fs-routes/pull/2](url)

**Comment by jsdevel** [comment]
Fixed in jsdevel/node-fs-routes/pull/2.
