### ISSUE TITLE
Filename with ":" is not supported in Windows

### ISSUE THREAD

**Issue by seveves** [kogosoftwarellc/express-openapi#4]
npm install express-openapi fails because it cannot create the file name ":id.js" from the sample-projects.

npm install express-openapi --save
npm ERR! tar.unpack untar error C:\Users\fries\AppData\Roaming\npm-cache\express-openapi\0.4.2\package.tgz
npm WARN EPACKAGEJSON express-openapi-example@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "express-openapi" "--save"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12
npm ERR! path C:\projects\misc-swagger-howto\nodejs\node_modules\.staging\express-openapi-2cbd6e854429c6f69613c40e36d233e3\test\sample-projects\basic-usage\api-routes\users\:id.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\projects\misc-swagger-howto\nodejs\node_modules\.staging\express-openapi-2cbd6e854429c6f69613c40e36d233e3\test\sample-projects\basic-usage\api-routes\users\:id.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\misc-swagger-howto\nodejs\npm-debug.log

**Comment by jsdevel** [comment]
Thanks @seveves!  I've removed the test directory from the published npm package.  I'm afraid I'll have to update the file format for windows though, to allow for something else.

**Comment by jsdevel** [comment]
@seveves with `v0.5.1`, `express-openapi` now expects filenames to be in the following format: `{id}.js`.  I've tested this on windows and unix flavors and it works great.  Let me know if you have any more issues.

**Comment by seveves** [comment]
Thank you. This works for me also! :+1:

**Comment by jsdevel** [comment]
Sweet!  Thanks for reporting back!
