### ISSUE TITLE
modular approach

### ISSUE THREAD

**Issue by troymolsberry** [kogosoftwarellc/express-openapi#45]
Hello, thank you for the excellent framework. I have a question about using it to construct modular express applications, where multiple routes are defined in individual npm modules, and the final product is composed from these. Can I call openapi.initialize() multiple times in a single app, once for each module? This implies that instead of a single routes folder, I may have several...

**Comment by jsdevel** [comment]
Give me some more details for your use case.  It sounds like maybe you have different versions of your API in separate directories, like `api-v1/` and `api-v2/` etc.  If that's the case, you can definitely call `.initialize()` with separate instances of your app and then have a parent app that you `parentApp.use(v1App` with.

**Comment by jsdevel** [comment]
> Can I call openapi.initialize() multiple times in a single app, once for each module

I haven't tried this, but it should work.

**Comment by troymolsberry** [comment]
My specific use case would be <company initiative #1> as a stand-alone npm module, and <company initiative #2> as a stand-alone npm module. Each of these modules would have a "routes" folder that conforms to the express-openapi format. There is a parent express project that is composed of all company initiatives (modules). Ultimately, I would like the parent api to behave exactly as though it had been built monolithically, with the rendered apiDocs, etc...

**Comment by jsdevel** [comment]
I see.  You should be able to run `initialize()` multiple times on the same app then.

**Comment by troymolsberry** [comment]
`var app = require('express')();
var openapi = require('express-openapi');
var async = require("async");

var modules = ['foo', 'bar'].map(function (module_name) {
    return require(module_name);
});
async.eachSeries(modules, function (module, cb) {
    openapi.initialize({
        apiDoc: require('./api/api.js'),
        app: app,
        routes: module.routes_directory
    });
    cb();
}, function (err) {

    app.use(function (err, req, res, next) {
        res.status(err.status).json(err);
    });

    app.listen(3000);

});
`

results in only foo routes appearing in the generated api documentation

**Comment by jsdevel** [comment]
> results in only foo routes appearing in the generated api documentation

I see.  Yea.  That would be an issue.

How about if `routes` can accept an `Array` of paths?  They'd have the same version prefix as outlined in your api-doc.  Would that work?

**Comment by troymolsberry** [comment]
absolutely would work, that was what I was originally hoping for

**Comment by jsdevel** [comment]
> absolutely would work, that was what I was originally hoping for

Sweet!  I'll try to have this implemented tonight.

**Comment by jsdevel** [comment]
@troymolsberry can you review #46?

**Comment by troymolsberry** [comment]
Smoke testing passed, I will now start digging in to building a modular api with this excellent framework. Thank you for the impressively rapid attention to this enhancement. Cheers

**Comment by jsdevel** [comment]
published as `v0.26.0` @troymolsberry !
