### ISSUE TITLE
external schemas appear to not render in swagger-ui

### ISSUE THREAD

**Issue by troymolsberry** [kogosoftwarellc/express-openapi#48]
running the test/sample-projects/with-external-schema-references app and viewing the generated api doc in swagger UI results in html markup displayed as well as errors implying that the external schemas could not be referenced.

Does express-openapi actually attempt to pull the schemas from the uris specified as the keys to the externalSchemas option object? Seems like the with-external-schema-references project inlines the definitions of the schema, and the uri is really just a key.

<img width="980" alt="screen shot 2016-09-02 at 11 54 43 pm" src="https://cloud.githubusercontent.com/assets/6516662/18223323/ce5ecfaa-7168-11e6-8999-9d9733cfc5f8.png">

**Comment by jsdevel** [comment]
looks like it isn't currently being bundled in the built api doc.  I think we could fix this easily, just need to know where in the api doc it should appear.

**Comment by jsdevel** [comment]
@troymolsberry also, see this: https://github.com/swagger-api/swagger-ui/issues/1592

It looks like this could be a bug in SwaggerUI

**Comment by troymolsberry** [comment]
agreed. express-openapi works perfectly here, and swagger-ui has two issues. External references that aren't hosted won't work, and it's displaying markup in it's ui for failed references.

**Comment by jsdevel** [comment]
Thanks for submitting the issue nonetheless!  This will be great for others facing similar issues.
