### ISSUE TITLE
Have case insensitive query parameters

### ISSUE THREAD

**Issue by casras** [kogosoftwarellc/express-openapi#49]
I know this is kind of against the open api documentation, but we are moving legacy public endpoints from .net (query params are case insensitive), and right now we have to disable input validation using "x-express-openapi-disable-validation-middleware", and then we read the parameters by below function: 

```
export function getCaseInsensitiveProperty(query: any, property: string): any {
    for (let p in query) {
        if (query.hasOwnProperty(p) && property.toLowerCase() === p.toLowerCase()) {
            return query[p];
        }
    }
    return null;
}
```

Meaning we can't benefit from validation rules we already wrote in the open api spec.

Any thoughts on this one?

BTW Great work.

**Comment by jsdevel** [comment]
> BTW Great work.

Thanks!

> Any thoughts on this one?

* If you have a list of query parameters that your .Net API expected, then you could normalize them in some pre API middleware before your API is reached.  Your parameter definitions could then use standard naming conventions that you prefer.
* We could add support for a vendor extension that would lowercase the parameters for you.  It would likely only work with flat input parameter structures, like query/header etc.

**Comment by casras** [comment]
If possible, a vendor extension would be nice. 

But again if I'm the only one facing this issue, I guess the pre middleware option would be the way to go.

**Comment by casras** [comment]
I have had a chance to look further into this, and right now I really miss an option to add middleware at least before validation.

A rough example:
`function(req, res, next) {
      if(!req || !req.operationDoc || !req.operationDoc.parameters) { next();return; }
      var names = req.operationDoc.parameters.map(x => { return x.name; })
      for(var i = 0; i < names.length; ++i) {
        var name = names[i];
        for(var p in req.query) {
          if(req.query.hasOwnProperty(p) && p.toLowerCase() === name.toLowerCase()) {
            req.query[name] = req.query[p];
            if(p!==name) { delete req.query[p]; }
          }
        }
      }
      next();
    }`

With regards to the list of query params, I'm not really happy about maintaining params in two places since they might get out of sync.

Let me know what you think, would you consider adding this as an optional middlware/vendor extension, or do you have other suggestions?

**Comment by jsdevel** [comment]
> With regards to the list of query params, I'm not really happy about maintaining params in two places since they might get out of sync.

I'd feel the same way.

> Let me know what you think, would you consider adding this as an optional middlware/vendor extension, or do you have other suggestions?

I think we could add a vendor extension for this.  It would look like this in your parameter definition:

```javascript
// my handler file
GET.apiDoc = {
  /*...*/
  parameters: [
    {
      name: 'somethingThatShouldBeCamelCase',
      in: 'query',
      required: true,
      'x-express-openapi-case-insensitive': true
    }
  ]
  /*...*/
};
```

I think this middleware could reside in this package as opposed to being in it's own repo.  We could probably do some optimization too being that we know during `initialize` what parameters need to be case insensitive.

```
function handleCaseInSensitivityMiddleware(location, properName) {
  var lowerCaseName = properName.toLowerCase();
  return function(req, res, next) {
    var obj = req[location];
    if (obj) {
      Object.keys(obj).forEach(function(name) {
           if (name.toLowerCase() === lowerCaseName) {
             obj[properName] = obj[name];
             delete obj[name];
           }
         }
      });
    }
    next();
  };
}
```

The trick is iterating over the parameters in `index.js` and adding the result of `handleCaseInSensitivityMiddleware(parameter.in, parameter.name)`.  I'd probably put `handleCaseInSensitivityMiddleware` in a `middleware` directory in this repo.

Can you submit a PR for this?

**Comment by casras** [comment]
I'll try, ASAP

**Comment by jsdevel** [comment]
@casras see `v0.29.0`.  `parameter` definitions now support `'x-express-openapi-case-sensitive': false`.

**Comment by casras** [comment]
Thanks a lot, I'll have a look at it when I'm back from vacation.
