### ISSUE TITLE
200 is invalid

### ISSUE THREAD

**Issue by notxt** [kogosoftwarellc/express-openapi#52]
Getting:
```
September 16 22:59:13: express-openapi:  validation errors [
  {
    "property": "instance.paths./provider.post.parameters[2]",
    "message": "is not exactly one from <#/definitions/parameter>,<#/definitions/jsonReference>",
    "schema": {
      "oneOf": [
        {
          "$ref": "#/definitions/parameter"
        },
        {
          "$ref": "#/definitions/jsonReference"
        }
      ]
    },
    "instance": {
      "name": "columns",
      "in": "body",
      "description": "Columns to include in response",
      "type": "array",
      "schema": {
        "$ref": "#/definitions/columnList"
      }
    },
    "name": "oneOf",
    "argument": [
      "<#/definitions/parameter>",
      "<#/definitions/jsonReference>"
    ],
    "stack": "instance.paths./provider.post.parameters[2] is not exactly one from <#/definitions/parameter>,<#/definitions/jsonReference>"
  },
  {
    "property": "instance.paths./provider.post.responses[200]",
    "message": "is not exactly one from <#/definitions/response>,<#/definitions/jsonReference>",
    "schema": {
      "oneOf": [
        {
          "$ref": "#/definitions/response"
        },
        {
          "$ref": "#/definitions/jsonReference"
        }
      ]
    },
    "instance": {},
    "name": "oneOf",
    "argument": [
      "<#/definitions/response>",
      "<#/definitions/jsonReference>"
    ],
    "stack": "instance.paths./provider.post.responses[200] is not exactly one from <#/definitions/response>,<#/definitions/jsonReference>"
  }
]
```
when I try to do the example in the `readme`

I'm a bit new to openapi but it seems like it's not recognizing `200` as a valid responses key, which I believe it should be

... michael

**Comment by jsdevel** [comment]
Can you change `type` to `$ref` for the `items` definition?

**Comment by jsdevel** [comment]
Updated the README.

**Comment by notxt** [comment]
works! there was one other little error that I put in a pr for

https://github.com/kogosoftwarellc/express-openapi/pull/53

**Comment by jsdevel** [comment]
Thanks a ton @notxt !  I hope you enjoy the framework.

**Comment by notxt** [comment]
oh I'm already loving it, I was a big fan of swagger via [hapi-swagger](https://github.com/glennjones/hapi-swagger) which I used at my old job. Just got a new one and they use express. It's taken me a minute find good equivalent but I'm liking your philosophy of `Stays as close to express as possible.`

How long has the project been around?

**Comment by jsdevel** [comment]
It's been around for about 9 months.  I developed it while at my last contract.  We started off using swaggerize-express, but found that one to be too buggy.  I wanted a framework that leveraged jsonschema which the main reason I wrote this.
