### ISSUE TITLE
Validation messaging

### ISSUE THREAD

**Issue by notxt** [kogosoftwarellc/express-openapi#54]
Liking this more and more so thanks for making such a stellar implementation. Question:

I'm not getting req validation messaging back - ( just 400s ) - can I enable that somehow?

**Comment by jsdevel** [comment]
Hmm.  Can you paste an example?

**Comment by notxt** [comment]
so for `#/parameters` I've got:

```
parameters: {
        pageNumber: {
            description: 'Page number requested',
            name: 'page',
            in: 'query',
            type: 'integer',
            minimum: 1,
            default: 1
        },
        resultsPerPage: {
            description: 'Number of results per page',
            name: 'resultsPerPage',
            in: 'query',
            type: 'integer',
            default: 100
        },
        providerFields: {
            description: 'Fields to include in result set',
            name: 'fields',
            in: 'query',
            type: 'array',
            items: {
                type: 'string',
                enum: [
                    'metadata',
                    'name',
                    'credentials',
                    'clinic'
                ]
            }
        },
    },
```
and when I put in bad input - ( ie "abc" instead "123" ) - I get a response like:

![validation](https://cloud.githubusercontent.com/assets/338020/18803658/e44dac16-81a6-11e6-96aa-a793328ef2ce.png)

and was wondering if there's a way to get messaging out. Something like 'bad parameter "page" must be an integer' or something

**Comment by notxt** [comment]
you know what ... it might be getting intercepted by my other middleware ...

**Comment by notxt** [comment]
so my middleware was a large part of it, but after removing all of it (to test) I was still getting:

![validation](https://cloud.githubusercontent.com/assets/338020/18804064/0fa12f10-81ab-11e6-9980-e02716ce5240.png)

I then added an [errorMiddleWare] override and started getting messaging. So maybe it's the default error handler running toString on the err object somewhere?

or my app could still be off for some reason, totally plausible

**Comment by jsdevel** [comment]
I'd start without any middleware.  Most of the sample projects in the test suite include examples with validation messages being returned.  It's also possible you initialized your app with an errorTransformer that isn't returning proper messages.

**Comment by notxt** [comment]
yeah ... there's something stinky in my app :(

sorry to bother, thanks for the quick response!

**Comment by jsdevel** [comment]
no bother at all!  I'm happy to be of help.
