### ISSUE TITLE
$ref external yaml file does not work

### ISSUE THREAD

**Issue by zcb22000** [kogosoftwarellc/express-openapi#69]
I use the dist folder files in master, and use $ref to reference external yaml file, but it can't resolved.
my yaml format is :

      parameters:
        -
          name: request
          in: body
          required: true
          schema:
            $ref: './deviceManageDF.yaml#/definitions/AddDeviceDTONA2Cloud'
even modified with full acess path as: 

      parameters:
        -
          name: request
          in: body
          required: true
          schema:
            $ref: 'http://localhost:8080/swagger-ui/deviceManageDF.yaml#/definitions/AddDeviceDTONA2Cloud'
It displayed: 
http://localhost:8080/swagger-ui/deviceManageDF.yaml#/definitions/AddDeviceDTOCloud2NA is not defined!

**Comment by zcb22000** [comment]
The response model alse shows not defined

**Comment by jsdevel** [comment]
@zcb22000 were you able to solve your issue?
