### ISSUE TITLE
Request validation sending [object Object] in Express response

### ISSUE THREAD

**Issue by kevipapo1** [kogosoftwarellc/express-openapi#77]
If I'm not mistaken, `express-openapi` is using `express-openapi-validation` by default and will validate requests to endpoints when the endpoint has given a value to the `apiDoc` parameter.

The validation is working correctly, but the response that a user receives is not helpful. Below is an example of what I get when hitting an endpoint with an improper request using Postman:

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>[object Object]</pre>
    </body>
</html>
```

Providing a custom `errorTransformer` function when initializing `express-openapi` doesn't solve the issue.

I've done some debugging and tracing and believe this issue is being caused by the way `express-openapi-validation` formats the error object it passes into `next()`. In short, the error object does not have a `stack` property and so `toString()` is called on the object before sending it out, resulting in the `[object Object]` we see in the response.

Maybe I'm missing some fundamental solution here, but it would be much nicer to have the response sent back as JSON, or at the very least a message that simply says "Incorrect data format received."

I can go into further detail and provide example code another time if you'd like.

**Comment by jsdevel** [comment]
@kevipapo1 this is very helpful!  I agree with you 100%.  Can you do some digging and possibly open a PR against `express-openapi-validation`?  If anything, perhaps a customer `toString` method should be added to output stringified JSON.

**Comment by kevipapo1** [comment]
Done! PR can be found [here](https://github.com/kogosoftwarellc/express-openapi-validation/pull/7).

**Comment by kevipapo1** [comment]
Also, for anyone in the future: you can add middleware to your Express app that handles all errors, including those from validation. This it the key line from the [express-openapi-validation](https://github.com/kogosoftwarellc/express-openapi-validation) README:

> If validation errors occur, `next` is called with `{status: 400, errors: [<validation errors>]}`.

You can add this code to the entry point of your node app and it will send the error object as JSON:

```javascript
app.use((err: any, req: express.Request, res: express.Response, next: express.NextFunction) => {
    if (err.status) {
        res.status(err.status);
    }
    if (err.errors) {
        res.json(err.errors);
    }
});
```

The above code will handle the error object that express-openapi-validation produces and respond with the list of validation errors as JSON.

**Comment by jsdevel** [comment]
Awesome!  Thanks @kevipapo1 !
