### ISSUE TITLE
Using "$ref: '#/definitions/...'" for responses has been deprecated.

### ISSUE THREAD

**Issue by XuluWarrior** [kogosoftwarellc/express-openapi#79]
All the examples in the test suite have API definitions similar to 

`
  responses: {
    default: {
      $ref: '#/definitions/Error'
    }
  }`

These are flagged as errors in the Swagger Editor.

A valid alternative is to use

`  responses: {
    default: {
      description: "Unexpected error",
      schema: {
        $ref: '#/definitions/Error'
      }
    }
  }
`

**Comment by jsdevel** [comment]
closed by #80
