### ISSUE TITLE
validation error for formData type boolean

### ISSUE THREAD

**Issue by phillip-hall** [kogosoftwarellc/express-openapi#8]
Given the following operation definition
```
{
    post: {
        summary: 'Application information',
        operationId: 'info',
        tags: ['/info'],
        parameters: [
            {
                name: 'booleanParam',
                in: 'formData',
                required: true,
                type: 'boolean',
                default: false
            }
        ],
        responses: {
            200: {
                description: 'Success',
                schema: {
                    $ref: '#/definitions/Success'
                }
            },
            default: {
                description: 'Error',
                schema: {
                    $ref: '#/definitions/Error'
                }
            }
        }
    }
}
```

and then calling using the following
`curl -X POST --header 'Content-Type: application/x-www-form-urlencoded' --header 'Accept: text/html' -d 'booleanParam=false' 'http://localhost:3200/api/info'`

the following error is returned
`error:  status=400, errors=[path=booleanParam, errorCode=type.openapi.validation, message=instance.booleanParam is not of a type(s) boolean, location=body]`

**Comment by jsdevel** [comment]
Do you have form parser middleware wired up?

**Comment by phillip-hall** [comment]
I have body-parser middleware setup as follows.

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

**Comment by jsdevel** [comment]
Hmm.  I'll have to do some testing around this.  Admittedly, for data isn't entirely tested.  Posting JSON in the body is though.

**Comment by jsdevel** [comment]
In the mean time, if you can submit a PR for a fix it would be greatly appreciated!

**Comment by phillip-hall** [comment]
OK.  The issue is in the express-openapi-coercion library.  It needs to build a formData coercer.

**Comment by jsdevel** [comment]
Ahh.  Good catch!  Sounds like a patch then.

**Comment by phillip-hall** [comment]
How do you do a patch?

Should I issue a PR on the express-openapi-coercion library?

**Comment by jsdevel** [comment]
> Should I issue a PR on the express-openapi-coercion library?

Yes.

**Comment by jsdevel** [comment]
> How do you do a patch?

Once `express-openapi-coercion` is updated, I'll update package.json for a patch release.  That should make your PR available everywhere.

**Comment by phillip-hall** [comment]
OK, PR is on its way.

**Comment by jsdevel** [comment]
Thanks!

**Comment by phillip-hall** [comment]
@jsdevel Did you see the 2 PR is submitted to the express-openapi-coercion project?  
When can they be merged and this project bumped?

**Comment by jsdevel** [comment]
I didn't!  Looking now.  I don't think I'm watching that repo (yet).

**Comment by jsdevel** [comment]
This was closed with https://github.com/kogosoftwarellc/express-openapi/commit/8d5b26ed10d62bf4c9d397492cb51dfda1c3f00e
