### ISSUE TITLE
Possibility to separate openapi-spec from http-controller

### ISSUE THREAD

**Issue by alrik** [kogosoftwarellc/express-openapi#87]
As far as i can see, the execution of any middleware like parameter validation happens based on the `apiDoc` property of a single http endpoint / route.

```js
module.exports.GET = () => {} // handler
module.exports.GET.apiDoc = {} // open api route schema
```

It would be nice if express-openapi could fallback to path-definitions passed to the `initialize({ apiDoc })` routine.

That way the developer could choose between having the route-handler and the api-spec in one file or separated.

I'd like to run the following setup:

```
api.js // openapi.initialize({ apiDoc: loadOpenApiSpec({ path: './' }), paths: './'})
api-doc.yml // swagger: 2.0 ...
paths/some-route/resource.js // module.export.GET = (req, res) => { ... }
paths/some-route/resource.yml // paths: { /some-route/resource: { get: { ... } } }
```
I would like to load and assemble the whole open-api spec with all path definitions just before passing it to `initialize`.

```js
const { sync: globSync } = require('glob');
const deepAssign = require('deep-assign');
const fs = require('fs');
const yaml = require('js-yaml');

module.exports = function loadOpenApiSpec({ version, path, specGlob = '/**/*.yml' }) {
  const files = globSync(specGlob, {root: path});

  const spec = {};

  files.forEach((file) => {
    deepAssign(spec, yaml.safeLoad(fs.readFileSync(file, 'utf8')));
  });

  spec.info.version = version;

  return spec;
};
```

So my idea is to keep backwards compatibility and to allow for populating the "global" spec down to a specific route. 

@jsdevel I could submit a PR if you like the idea.

**Comment by jsdevel** [comment]
@alrik I feel supporting the path handler's apiDocs separate would be good.  Instead of having to do something during initialize, what bout something like this?

```
./api-v1/users.js
./api-v1/users.GET.yml
...
```

Then we could tweak the startup logic to have logic like `operationApiDoc = methodHandler.apiDoc || fs.existsSync(path+method+'.yml') && /* pull in file */`.  Thoughts?

**Comment by alrik** [comment]
My idea was to implement it like:
```
 var operationDoc = getMethodDoc(operationHandler)) || pathItem[METHOD_ALIASES[methodName]];
```
This seems to me to be the most flexible and unopinionated way.

But both approached do not exclude each other.

**Comment by jsdevel** [comment]
Yes!  I agree, that would be the most flexible.
