### ISSUE TITLE
BasePath problems with empty string vs '/'

### ISSUE THREAD

**Issue by saborrie** [kogosoftwarellc/express-openapi#90]
My application doesn't have anything like '/v1', for a basePath. I need either '' or '/'.
Unfortunately neither option is completely problem free while using express-openapi:

If I set it to '/', I get routing problems, my routes are defined like:
```
openapi.initialize({
  app,
  ...
  paths: [
    {
      path: '/auth/token',
      module: require('./auth_token')
    },
    ...
  ]
});
```
If I have a leading '/' in the path for my module, then the route ends up being set up as '//auth/token', which obviously breaks things. If I don't have the leading '/' in the path, I get this error: ` Error: express-openapi: args.apiDoc was invalid after populating paths.`

Alternatively, if I set basePath to '' (or don't set it, as express-openapi defaults it to '') then I can get routing to work, however SwaggerUI will report a problem with the basePath being invalid (supposed to match '^/'), 

I've resolved the problem as far as running my application by setting basePath to '' while letting express-openapi set up, and then intercepting the api docs for SwaggerUI with the following hack:

```
app.use('/api-doc.json', (req, res, next) => {
  const json = res.json;
  res.json = function(obj) {
    obj.basePath = '/';
    json.apply(res, arguments);
  };
  next();
});
```

**Comment by jsdevel** [comment]
Can you submit a PR?  I agree that `basePath: '/'` should be allowed.  I think the issue is that `fs-routes` gives `/` as a prefix.

**Comment by bugeats** [comment]
I just hit this snag during my first hour with this project. Very unintuitive.
<img width="353" alt="screen shot 2018-04-27 at 2 50 11 pm" src="https://user-images.githubusercontent.com/33055/39386606-521ed27c-4a2a-11e8-930c-c7f8ab1664e3.png">

**Comment by jsdevel** [comment]
@saborrie @bugeats can you guys try with the latest?

**Comment by bugeats** [comment]
Works as expected now, thanks.
