### ISSUE TITLE
Directory structure for a nested paths 

### ISSUE THREAD

**Issue by abrinckm** [kogosoftwarellc/express-openapi#93]
Hi I'm noob, 

The paths I want look something like this:

`/v1/resource/{type}/`
`/v1/resource/{type}/something`

I assume I'll need this directory structure : 
```
|-<package>
    |-v1
        |-resource
            |-{type}
                |-index.js
                |-something.js
```

however it doesn't seem to be working. It is returning 404 for either endpoint.
The documentation only helps with a specific type of nested pattern and doesn't have any further examples for this particular pattern I'm having trouble with.

I have tried various other directory structures including...

```
|-resource
    |-{type.js}
    |-{type}
        |-something
```

but that didn't help either

**Comment by abrinckm** [comment]
Nevermind. I answered my own question. The bottom example works just fine. I must've done something wrong when testing the first time.

**Comment by abrinckm** [comment]
To clarify... The problem I had, (which I corrected in my original comment), and the reason it wasn't working for me, was that I had the file named incorrectly:

Wrong: `{type.js}`
Correct: `{type}.js`

**Comment by jsdevel** [comment]
Thanks @abrinckm !
